# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_councilprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pointer',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
